[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "tag-prefix/$version"
version_scheme = "semver"
version = "0.0.2"
major_version_zero = true   # only for development
update_changelog_on_bump = true
version_files = [
    "products/__version__.py",
]

[tool.commitizen.changelog]
incremental = false              # Ensure it processes all commits, not just the latest
prepend = true                   # Prepend new changelog entries to the file
changelog_file = "CHANGELOG.md"  # Specify the changelog file name
