name: Load and print config variables
on:
  push:
    branches:
      - 'services/**'

jobs:
  get_product_dir:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Get product dir from branch name
    outputs:
      product_dir: ${{ steps.from_branchname.outputs.product_dir }}
    steps:
      - name: Product directory name from branch
        id: from_branchname
        # run this on every push to the services branch
        env:
          # github.event_name == 'push', use github.ref_name iro github.ref
          # github.ref and github.ref_name appear to be the same on push events
          #
          BRANCH: ${{ github.ref }}
        run: |
          CUSTOMER_FOLDER=$(dirname ${BRANCH#*heads/})
          ZENDESK_TCKT_NO=$(cut -d '-' -f 1 <<< ${BRANCH##*/})
          echo products/${CUSTOMER_FOLDER}/${ZENDESK_TCKT_NO}
          echo "product_dir=products/${CUSTOMER_FOLDER}/${ZENDESK_TCKT_NO}" >> $GITHUB_OUTPUT
          echo $product_dir
  print_config_vars:
    name: Print vars loaded from config.json
    uses: ./.github/workflows/config_from_file.yml
    needs: get_product_dir
    with:
      PRODUCT_DIR: ${{ needs.get_product_dir.outputs.product_dir }}