name: Get GHA context on PR close
on:
  pull_request:
    types:
      - closed
      - opened
    paths:
        # build envspecs if files are added/updated or a new tag is created
        - 'products/**'
    branches:
      # if sample-proj is updated; update the envspec and create a PR
      - '**'

jobs:
  get_gha_context:
    name: update sampleproj envspecs & open PR if applicable
    runs-on: ubuntu-latest
    steps:
    - name: Print context vars; merge to main
      if: github.event.pull_request.merged == true
      run: |
        echo "ONLY ON MERGE TO MAIN"
        echo "github.ref_name": ${{ github.ref_name }}
        echo "github.head_ref": ${{ github.head_ref}}
        echo "github.event.number": ${{ github.event.number }}
    - name: Print context vars on PR
      run: |
        echo "PR opened"
        echo "github.ref_name": ${{ github.ref_name }}
        echo "github.head_ref": ${{ github.head_ref}}
        echo "github.event.number": ${{ github.event.number }}
    - name: Debug
      uses: mxschmitt/action-tmate@v3