name: Get GHA context
on:
  pull_request:
    paths:
      - 'products/**'
    branches:
      - 'test/**'
  push:
    tags:
      - '*'

jobs:
  get_gha_context:
    name: dump_gha_context
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: Print context vars; merge to main
      if: github.event.pull_request.merged == true
      run: |
        echo "ONLY ON MERGE TO MAIN"
        echo "github.ref_name": ${{ github.ref_name }}
        echo "github.head_ref": ${{ github.head_ref}}
        echo "github.event.number": ${{ github.event.number }}
    - name: Print context vars on PR
      run: |
        echo "PR opened"
        echo "github.ref_name": ${{ github.ref_name }}
        echo "github.head_ref": ${{ github.head_ref}}
        echo "github.event.number": ${{ github.event.number }}
    #- name: Debug
    #  uses: mxschmitt/action-tmate@v3