name: Get GHA context
on:
  pull_request:
    types:
      - closed
    paths:
      - 'products/**'
    branches:
      - 'main'
  # push:
  #   branches:
  #     - 'main'
  #   tags:
  #     - '*'

permissions:
  contents: write
  pull-requests: write

jobs:
  get_gha_context:
    name: dump_gha_context
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: Print context vars; merge to main
      if: github.event.pull_request.merged == true
      run: |
        echo "ONLY ON MERGE TO MAIN"
        echo "github.ref_name": ${{ github.ref_name }}
        echo "github.head_ref": ${{ github.head_ref}}
        echo "github.event.number": ${{ github.event.number }}
    - name: Print context vars on PR
      run: |
        echo "PR opened"
        echo "github.ref_name": ${{ github.ref_name }}
        echo "github.head_ref": ${{ github.head_ref}}
        echo "github.event.number": ${{ github.event.number }}
  open_pr:
    name: dump_gha_context
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        fetch-depth: 0
    - name: add a test file
      run: |
        echo "Added by PR#" ${{ github.ref_name }} >> products/test_file.txt
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@70a41aba780001da0a30141984ae2a0c95d8704e # v6.0.2
      with:
        # context is for creatinga  PR where base is main.
        #   github.head_ref - name of the branch that has been merged
        #   github.event.number - # of the PR that was just merged
        token: ${{ secrets.PR_PAT }}
        branch: pr-after-merge/${{ github.head_ref }}
        title: Updates to envspec from merging PR#${{ github.event.number }}
        body: |
          - Created upon merge of: [PR#${{ github.event.number }}](https://github.com/sandhujasmine/ExploreGhActions/pull/${{ github.event.number }})
          - Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
        labels: |
          automation
          ${{ github.ref_name }}
    #- name: Debug
    #  uses: mxschmitt/action-tmate@v3