name: Update conda recipe and build configuration
on:
  pull_request:
    #types:
    #  - closed
    #paths:
    #    - 'path-trigger/**'
    branches:
      - 'main'

# added for testing
  workflow_dispatch:

jobs:
  build_config:
    if: github.event.pull_request.merged == true
    name: Update build configuration
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: get short git hash
      id: get_version
      run: |
        from datetime import datetime
        import subprocess
        import os

        GITHUB_OUTPUT = os.getenv('GITHUB_OUTPUT')
        result = subprocess.run(
          ["git", "rev-parse", "--short", "HEAD"],
          capture_output=True,
          text=True,
          check=True,
        )
        short_hash = result.stdout.strip()
        version = f"{datetime.today().strftime('%Y.%m.%d')}+{short_hash}"
        with open(GITHUB_OUTPUT, 'w') as fp:
          fp.write(f"VERSION={version}")
      shell: python
    - name: Generate conda-recipe & pyproject with this version
      env:
        VERSION: ${{ steps.get_version.outputs.VERSION }}
      run: |
        echo "Update: $VERSION" >> path-trigger/foo
      shell: bash
    - name: Debug
      env:
        VERS: ${{ steps.get_version.outputs.VERSION }}
        TOKEN: ${{ secrets.TEST_TOKEN }}
      uses: mxschmitt/action-tmate@v3
    - name: Create PR with recipe updates
      if: false
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        # context is for creating a PR where base is main.
        #   github.head_ref - name of the branch that has been merged
        #   github.event.number - # of the PR that was just merged
        token: ${{ secrets.TEST_TOKEN }}
        branch: update-agent-api-wrapper/${{ github.head_ref }}
        title: Build spec update from PR#${{ github.event.number }}
        body: |
          - Created upon merge of: [PR#${{ github.event.number }}](https://github.com/${{ github.event.repository }}/pull/${{ github.event.number }})
          - Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
        labels: |
          automation
          ${{ github.ref_name }}
