name: Update conda recipe and build configuration
on:
  pull_request:
    types:
      - closed
    paths:
        - 'path-trigger/**'
    branches:
      - 'main'

  workflow_dispatch:  # manual trigger for testing only
    inputs:
      debug:
        description: 'ssh session to debug'
        required: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  build_config:
    if: >
      github.event.pull_request.merged == true ||
      github.event_name == 'workflow_dispatch'
    name: Update build configuration
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: get short git hash
      id: get_version
      run: |
        from datetime import datetime
        import subprocess
        import os

        GITHUB_OUTPUT = os.getenv('GITHUB_OUTPUT')
        result = subprocess.run(
          ["git", "rev-parse", "--short", "HEAD"],
          capture_output=True,
          text=True,
          check=True,
        )
        short_hash = result.stdout.strip()
        version = f"{datetime.today().strftime('%Y.%m.%d')}+{short_hash}"
        with open(GITHUB_OUTPUT, 'w') as fp:
          fp.write(f"VERSION={version}\n")
          fp.write(f"SHORT_HASH={short_hash}")
      shell: python
    - name: Generate conda-recipe & pyproject with this version
      env:
        VERSION: ${{ steps.get_version.outputs.VERSION }}
      run: |
        echo "$VERSION" > version.txt
      shell: bash
    - name: Debug
      if: ${{ github.event.inputs.debug == 'true' }}
      env:
        VERS: ${{ steps.get_version.outputs.VERSION }}
        PR_URL: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
        PRNUM: PR#${{ github.event.number }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_CONTEXT: ${{ toJson(github) }}
      uses: mxschmitt/action-tmate@v3
    - name: Create PR
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EVENT: ${{ github.event_name }}
        BRANCH_PRE: build-config-${{ steps.get_version.outputs.SHORT_HASH }}
      run: |
        set -euxo pipefail
        if [[ "$EVENT" == "workflow_dispatch" ]]; then
          BRANCH=$BRANCH_PRE/workflow_dispatch
          TITLE="Build specs updated manually"
          BODY="- Created by manual trigger"
        else
          PR=${{ github.event.number }}
          REPO=${{ github.repository }}
          BRANCH=$BRANCH_PRE/${{ github.head_ref }}
          TITLE="Build specs updates from PR: ${PR}"
          BODY="- Created after merging [PR#${PR}](https://github.com/${REPO}/pull/${PR})"
        fi

        git config --global user.email "you@example.com"
        git config --global user.name "PR-bot"
        git checkout -b $BRANCH
        git commit -a -m "updated path-trigger/foo"
        git push -u origin $BRANCH
        gh pr create -B main --title "$TITLE" --body "$BODY"
      shell: bash
    #  if: false
    #  id: cpr
    #  uses: peter-evans/create-pull-request@v7
    #  with:
    #    # context is for creating a PR where base is main.
    #    #   github.head_ref - name of the branch that has been merged
    #    #   github.event.number - # of the PR that was just merged
    #    token: ${{ secrets.TEST_TOKEN }}
    #    branch: update-agent-api-wrapper/${{ github.head_ref }}
    #    title: Build spec update from PR#${{ github.event.number }}
    #    body: |
    #      - Created upon merge of: [PR#${{ github.event.number }}](https://github.com/${{ github.event.repository }}/pull/${{ github.event.number }})
    #      - Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
    #    labels: |
    #      automation
    #      ${{ github.ref_name }}
