name: Print Github Env Variables
on:
  pull_request:
    branches:
      - 'services/**'
  push:
    branches:
      - 'services/**'
  workflow_dispatch:

env:
  INSTALLER_NAME: ${{ GITHUB_REF }}

jobs:
  print-env-variabes:
    name: Print Github Variables
    runs-on: ubuntu-latest
    steps:
      - name: Print Github Variables
        run: |
          echo "GITHUB_REF:$GITHUB_REF"
          echo "GITHUB_HEAD_REF:$GITHUB_HEAD_REF"
          echo "GITHUB_SHA:$GITHUB_SHA"
          echo "GITHUB_WORKFLOW:$GITHUB_WORKFLOW"
          echo "GITHUB_EVENT_NAME:$GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH:$GITHUB_EVENT_PATH"
          echo "GITHUB_WORKSPACE:$GITHUB_WORKSPACE"
          echo
          echo "From GITHUB_REF:${GITHUB_REF##*/}"
          echo "From GITHUB_HEAD_REF:${GITHUB_HEAD_REF##*/}"
          echo "From GITHUB_BASE_REF:${GITHUB_BASE_REF##*/}"
          echo
          echo "INSTALLER_NAME:${INSTALLER_NAME}"

      - name: Print complete webhook event payload
        run: cat $GITHUB_EVENT_PATH
