name: Print Github Env Variables
on:
  pull_request:
    branches:
      - 'services/**'
  push:
    branches:
      - 'services/**'
  workflow_dispatch:

jobs:
  installer_name:
    name: Set installler_name
    runs-on: ubuntu-latest
    outputs:
      installer_name: ${{ steps.leaf.outputs.branch }}
    steps:
      - name: Get leaf of branch name
        env:
          BRANCH: ${{ github.ref_name }}
        id: leaf
        run: echo "branch=${BRANCH##*/}" >> $GITHUB_OUTPUT
  svc_installer:
    name: setup svc instalelr
    uses: ./.github/workflows/svc-installer.yml
    needs: installer_name
    with:
      INSTALLER_NAME: ${{ needs.installer_name.outputs.installer_name }}
