name: Print Github Env Variables
on:
  push:
    branches:
      # when PR is merged into main, it is a push event
      - main
      - 'services/**'
  workflow_dispatch:

jobs:
  installer_name:
    name: Set installler_name
    runs-on: ubuntu-latest
    outputs:
      installer_name: ${{ steps.leaf.outputs.branch }}
    steps:
      - name: Get leaf of branch name
        env:
          # github.head_ref should exist only when PR is merged?
          BRANCH: ${{ github.head_ref || github.ref_name }}
        id: leaf
        run: echo "branch=${BRANCH##*/}" >> $GITHUB_OUTPUT
      - name: echo event name
        run: |
          echo "GITHUB_EVENT_NAME: " ${{ github.event_name }}
  svc_installer:
    # if: startsWith( ${{ github.head_ref }}, "refs/heads/services")
    name: Setup svc installler
    uses: ./.github/workflows/svc-installer.yml
    needs: installer_name
    with:
      INSTALLER_NAME: ${{ needs.installer_name.outputs.installer_name }}
