name: Print Github Env Variables
on:
  pull_request:
    # to run CI after branch is merged into main
    types:
      - closed
  push:
    branches:
      - main
      - 'services/**'
  workflow_dispatch:

jobs:
  installer_name:
    name: Set installler_name
    runs-on: ubuntu-latest
    outputs:
      installer_name: ${{ steps.leaf.outputs.branch }}
    steps:
      - name: Get leaf of branch name
        env:
          # github.head_ref should exist only when PR is merged?
          BRANCH: ${{ github.head_ref || github.ref_name }}
        id: leaf
        run: echo "branch=${BRANCH##*/}" >> $GITHUB_OUTPUT
  svc_installer:
    # do this on all push events or when a services PR is merged
    if: github.event_name == 'push' || (github.event.pull_request.merged == true && contains( ${{ github.head_ref }}, "services")
    name: Setup svc installler
    uses: ./.github/workflows/svc-installer.yml
    needs: installer_name
    with:
      INSTALLER_NAME: ${{ needs.installer_name.outputs.installer_name }}
