name: Services installer

on:
  workflow_call:
    inputs:
      INSTALLER_NAME:
        description: 'Name of the installer (e.g., Anaconda3, Miniconda3)'
        type: 'string'
        required: true

jobs:
  echo_name:
    runs-on: ubuntu-latest
    name: Set installer_name
    environment:
      name: ${{ inputs.ENVIRONMENT }}

    steps:
    - name: Check env vars
      run: echo "INSTALLER_NAME: ${{ inputs.INSTALLER_NAME }}"
